### ISSUE TITLE
`part-one` qismidagi link aslida matn bo'lishi kerak.

### ISSUE THREAD

**Issue by darxanov** [MIRZOULUGBEK9008/intro-selfmade#1]
![image](https://user-images.githubusercontent.com/99054718/160402073-3a147ff6-6ad6-4cae-bbc3-8fb612a27c67.png)

Manashu elementga `a` tegi o'rniga `p` tegi yozilgani ma'qul.

**Comment by MIRZOULUGBEK9008** [comment]
Ok tushunarli, lekin men link qilishni ma'qul ko'rdim sababi agar kidir ustiga bosganda yana qaytib shu page ni o'zi ochiladi "tipa"  logo sifatida..
